### ISSUE TITLE
Possible new features

### ISSUE THREAD

**Issue by PhilippKrone** [FaridSafi/react-native-gifted-listview#1]
Hi,

I've just implemented to following additions:

1) Support for listviews with sections
2) Triggering refresh from external (onRefresh() calling _onRefresh())
3) Passing an additional options object to onFetch giving information about whether its the first onFetch or whether the onFetch is triggered from external (using onRefresh()).

Are you interested in a PR here? And if yes, for which topics? :)

Regards
Philipp

P.S. Really nice component! :)

**Comment by FaridSafi** [comment]
Hello Philipp, thank you for your features suggestions.
Yes i'm interested in a PR for all of these topics

**Comment by PhilippKrone** [comment]
@FaridSafi Please take a look at https://github.com/FaridSafi/react-native-gifted-listview/pull/2 :)

**Comment by FaridSafi** [comment]
https://github.com/FaridSafi/react-native-gifted-listview/releases/tag/v0.0.3 :) 
Thanks @PhilippKrone !
