### ISSUE TITLE
Warning: GiftedListView: isMounted is deprecated. 

### ISSUE THREAD

**Issue by macoto-liu** [FaridSafi/react-native-gifted-listview#109]
"react": "16.0.0-alpha.12",
"react-dom": "16.0.0-alpha.12",
"react-native": "^0.46.1",
"react-native-gifted-listview": "0.0.15",

> 07-14 06:14:10.770  2312  2411 W ReactNativeJS: Warning: GiftedListView: isMounted is deprecated. Instead, make sure to clean up subsc
> riptions and pending requests in componentWillUnmount to prevent memory leaks.

**Comment by SunflowerGJ** [comment]
I meet this warning too，waiting solved method！

**Comment by xyy7260** [comment]
I met the same way, but I hope the author will come out and have a look

**Comment by sir-gon** [comment]
You can try my fork if author don't merge my pull request :B
