### ISSUE TITLE
It should not fire events when i drag the view to the initial position

### ISSUE THREAD

**Issue by Creemli** [FaridSafi/react-native-gifted-listview#12]
When I pull down and then pull up back to the normal position, it fires the refresh event. Maybe user just don't want to refresh in this time.

**Comment by FaridSafi** [comment]
Hello,
I imitated the Facebook iOS pull to refresh.
https://github.com/FaridSafi/react-native-gifted-listview/blob/master/GiftedListView.js#L351
The difference between refreshableViewHeight and refreshableDistance is the distance before triggering the refresh

**Comment by zccan** [comment]
@FaridSafi  refreshableDistance do not exists anymore?
