### ISSUE TITLE
typeError: expected dynamic type double but had type null

### ISSUE THREAD

**Issue by zhbhun** [FaridSafi/react-native-gifted-listview#20]
As this commit [use new scrollTo() API call since react-native 0.20](https://github.com/FaridSafi/react-native-gifted-listview/commit/e5b6d1ffe4249e430a74fe80bf18040f7eac8bd1), result in react-native-gifted-listview not work with React Native before 0.20.0. But README.md just mention "0.0.12 RN 0.20.0 support (PR @akiver)".

**Comment by FaridSafi** [comment]
Hello @zhbhun
If I understand, the error says that the value of this.props.refreshableViewHeight is null ?

**Comment by SpaceK33z** [comment]
@FaridSafi, I removed the code in the commit @zhbhun mentioned, so I think this ticket can be closed as well :).

**Comment by FaridSafi** [comment]
thank you @SpaceK33z
