### ISSUE TITLE
Loading indicator not appearing smoothly

### ISSUE THREAD

**Issue by skleest** [FaridSafi/react-native-gifted-listview#21]
if I use setTimeout in _onFetch as shown in example, loading indicator animations works well. However, in my code below using an api call (RN Fetch):

  _onFetch(page, callback, options) {
    if (options.firstLoad){
      callback(alreadyLoadedItems)
    } else {
      Api.getFeed().then((newItems) => {callback(newItems))
    }
  }

Listview release hides the refreshableView for a second, then loading indicator appears. This temporarily removes height of refreshableView (50), and although animations are still smooth, it's not the experience users are used to. Any help here? Thank you.

**Comment by FaridSafi** [comment]
fixed by 0.0.13
