### ISSUE TITLE
I got a Warining:Each child in an array or iterator should have a unique "key" prop.....

### ISSUE THREAD

**Issue by yaoyonstudio** [FaridSafi/react-native-gifted-listview#27]
I got a Warining:Each child in an array or iterator should have a unique "key" prop.....

I fetch data from API, the data show,and I got this warning. 
How to remove it ?
thanks.

**Comment by magrinj** [comment]
I remove this warning by adding the props `key` in my separator render function and generate this key with the `sectionID` and the `rowID`, like that:

in the `_renderSeparatorView` function:

``` jsx
  _renderSeparatorView(sectionID, rowID) {
    return (
      <View key={`${sectionID}-${rowID}`} style={ styles.separator } />
    );
  }
```

in the `GiftedListView` component:

``` jsx
<GiftedListView
     renderSeparator={ (sectionID, rowID) => this._renderSeparatorView(sectionID, rowID) }
/>
```

**Comment by yaoyonstudio** [comment]
Hi ! Thank you for reply .
I try it , and I got another  Warning: flattenChildren(...): Encountered...

My data already have a "ID" field, but I don't know how to pass that ID to be a "rowID" on each row , I try use the "key={rowData.id}" in the TouchableHighlight tag,but doesn't work.

here's my code . and the _renderSeparatorView part is exactly like yours.

```
if(rowData.thumbnailurl){
    return (
        <TouchableHighlight
            key={rowData.id}
            style={customStyles.row}
            underlayColor='#c8c7cc'
            onPress={() => this._onPress(rowData)}
            >
            <View style={customStyles.PostItem}>
                <Image source={{uri:rowData.thumbnailurl}} style={customStyles.PostThumbnail} />
                <View style={customStyles.PostText}>
                    <Text style={customStyles.PostTitle}>{rowData.title.rendered}</Text>
                    <Text style={customStyles.PostDate}>{rowData.date.substring(0,10)}</Text>
                </View>
            </View>
        </TouchableHighlight>
    );
}
```

How to do ? Thanks.

**Comment by magrinj** [comment]
Hi, the `flattenChildren(...)` error indique that you have multiple children with the same key.
So just try to remove the props `key` in your `TouchableHighlight` or if you want to keep the key, add two parameters to your function `_renderRow` like that:

``` jsx
_renderRow(rowData, sectionID, rowID) {
  // Your stuff
}
```

and change the props `key` with that: 

``` jsx
 key={`${sectionID}-${rowID}`}
```

I think that's gonna work now :)

**Comment by yaoyonstudio** [comment]
I just try  , and doesn't work  again.
And I try some debugging, turns out I can't get the key with {`${sectionID}-${rowID}`}, a little weired.
and when I try {section} or {rowID} , It works. 

since I don't want it with Sections,so here my code.
`<View key={rowID} style={customStyles.separator} />
`
problem solved.
your code ( _renderRow(rowData, sectionID, rowID) ) Inspire me to get through this. 

Thank you very much.

**Comment by magrinj** [comment]
@yaoyonstudio: Perfect :)
