### ISSUE TITLE
PullToRefreshViewAndroid is deprecated

### ISSUE THREAD

**Issue by SpaceK33z** [FaridSafi/react-native-gifted-listview#28]
`PullToRefreshViewAndroid` is no longer necessary; it has been replaced by `RefreshControl` which works on both platforms.

As of 0.22 (in RC now), `PullToRefreshViewAndroid` [will be deprecated](https://github.com/facebook/react-native/commit/91788d2bbd35a530269664c71cd17220cc7bc80a).

**Comment by SpaceK33z** [comment]
@FaridSafi, I'm planning to make a PR for this. Would you review it? A small downside of `RefreshControl` is that you lose some customizing options, but I think it's worth it.

**Comment by FaridSafi** [comment]
thank you, new version has been published
