### ISSUE TITLE
The refreshing spinner will not disapear even if I have callbacked in onFetch sometimes

### ISSUE THREAD

**Issue by blankzust** [FaridSafi/react-native-gifted-listview#35]
![image](https://cloud.githubusercontent.com/assets/8541906/14074131/580998c8-f501-11e5-8a24-8ed1d97f324e.png)
When I first enter the view.
![image](https://cloud.githubusercontent.com/assets/8541906/14074219/01eaeef0-f502-11e5-85c7-89b604b88c20.png)
When I refresh.

In fact, I have callbacked in onFetch when refreshing.
![image](https://cloud.githubusercontent.com/assets/8541906/14074178/b6f5e774-f501-11e5-9381-160366b1cc79.png)
And the console has printed the message
![image](https://cloud.githubusercontent.com/assets/8541906/14074214/f131a144-f501-11e5-9d7a-18c1751a39e5.png)

But the spinner don't disapear.Could you please give me some ideas

**Comment by blankzust** [comment]
Hear is my code:
`onFetch(page = 1, callback, options) {
        setTimeout(() => {
            fetch(keys.newApi, {
                method: 'POST',
                headers:{
                    'Accept': 'application/json',
                    'Content-Type': 'application/x-www-form-urlencoded'
                },
                timeout: 10000,
                body: 'content=' +
                    JSON.stringify({
                        data: {
                            userId: 230607, 
                            type: 2, 
                            courseId: 230932, 
                            pageNumber: page, 
                            pageSize: 10, 
                            isDuetime: false
                        }, 
                        header: {
                            appseq: "",
                            trcode: "EM00017",
                            trdate: new Date(),
                        }
                    })
            })
            .then((response) => response.json())
            .then(responseData => {
                if(responseData.data === null) {
                    callback(null);
                    console.log(responseData);
                } else {
                    callback(responseData.data.list);
                }
            })
            .catch(err => console.log(err))
            .done();
        }, 100);`

**Comment by blankzust** [comment]
Here are my codes:
onFetch(page = 1, callback, options) {
        setTimeout(() => {
            fetch(keys.newApi, {
                method: 'POST',
                headers:{
                    'Accept': 'application/json',
                    'Content-Type': 'application/x-www-form-urlencoded'
                },
                timeout: 10000,
                body: 'content=' +
                    JSON.stringify({
                        data: {
                            userId: 230607, 
                            type: 2, 
                            courseId: 230932, 
                            pageNumber: page, 
                            pageSize: 10, 
                            isDuetime: false
                        }, 
                        header: {
                            appseq: "",
                            trcode: "EM00017",
                            trdate: new Date(),
                        }
                    })
            })
            .then((response) => response.json())
            .then(responseData => {
                if(responseData.data === null) {
                    callback(null);
                    console.log(responseData);
                } else {
                    callback(responseData.data.list);
                }
            })
            .catch(err => console.log(err))
            .done();
        }, 100);

**Comment by blankzust** [comment]
`onFetch(page = 1, callback, options) {
        setTimeout(() => {
            fetch(keys.newApi, {
                method: 'POST',
                headers:{
                    'Accept': 'application/json',
                    'Content-Type': 'application/x-www-form-urlencoded'
                },
                timeout: 10000,
                body: 'content=' +
                    JSON.stringify({
                        data: {
                            userId: 230607, 
                            type: 2, 
                            courseId: 230932, 
                            pageNumber: page, 
                            pageSize: 10, 
                            isDuetime: false
                        }, 
                        header: {
                            appseq: "",
                            trcode: "EM00017",
                            trdate: new Date(),
                        }
                    })
            })
            .then((response) => response.json())
            .then(responseData => {
                if(responseData.data === null) {
                    callback(null);
                    console.log(responseData);
                } else {
                    callback(responseData.data.list);
                }
            })
            .catch(err => console.log(err))
            .done();
        }, 100);`

**Comment by blankzust** [comment]
Now,it is solved.Anyway,Thank you.

**Comment by mfuruskog** [comment]
I think I got the same problem @blankzust, how did you solve it?

**Comment by sjafri5** [comment]
ran into this as well
you have to pass the array you want to return in the callback paramater:

```
onFetch(page=1, callback, options) {
  return api.foo().then((response) => {
    return callback(response.dicks)
  })
};
```
