### ISSUE TITLE
Consider using PullToRefreshLayoutAndroid

### ISSUE THREAD

**Issue by mrcasals** [FaridSafi/react-native-gifted-listview#4]
Just a few hours ago Facebook released the `PullToRefreshLayoutAndroid` component. Consider using it for the Android version.

This is the commit with the release: https://github.com/facebook/react-native/commit/37f81341a006458d84d934882485c2a0a8838497 It just landed on master, so it won't be released until v0.17, I guess.

**Comment by FaridSafi** [comment]
Great! I will definitely look at it.
Thank you for this information.

**Comment by mrcasals** [comment]
You're welcome, thanks for your work and making all these repos open-source! :clap: :clap: :clap: :clap:

**Comment by FaridSafi** [comment]
my pleasure :)
more to come soon!

**Comment by FaridSafi** [comment]
Hello, I published a new version with PullToRefreshViewAndroid support

**Comment by mrcasals** [comment]
Awesome, thank you!
