### ISSUE TITLE
Update react-native-gifted-spinner to 0.0.5

### ISSUE THREAD

**Issue by yukunwu** [FaridSafi/react-native-gifted-listview#50]
Hi,
   Please update  react-native-gifted-listview's dependency  react-native-gifted-spinner to v0.0.5,make it suitable to RN28.0

**Comment by Leon1108** [comment]
+1

**Comment by habovh** [comment]
Or simply use `ActivityIndicator` as suggested by deprecation logs. @FaridSafi already warned that [react-native-gifted-spinner](https://github.com/FaridSafi/react-native-gifted-spinner) should not be used anymore in favour of `ActivityIndicator`. I think it's just a matter of time that it gets updated. You can probably PR as well.

**Comment by yukunwu** [comment]
Yeah,I have fork it,and update it,maybe I will create a PR.
