### ISSUE TITLE
Funky static spinner appearing on every first run

### ISSUE THREAD

**Issue by kdenz** [FaridSafi/react-native-gifted-listview#54]
<img width="376" alt="screen shot 2016-07-08 at 5 04 29 pm" src="https://cloud.githubusercontent.com/assets/12795428/16682801/edc595f6-452e-11e6-876e-a6c0194e71db.png">
As seen at the top right corner.
It disappears if I switch around pages, but it's there for every startup occasion.
I'm using RN27.2 and the code is from the simple example.

**Comment by kokororin** [comment]
delete `refreshableTintColor="blue"` fixed it.

**Comment by kdenz** [comment]
Thanks!!
