### ISSUE TITLE
Render empty view

### ISSUE THREAD

**Issue by Shakarang** [FaridSafi/react-native-gifted-listview#55]
Hey ! 
I'm running your advanced example and I would like to know how to tell your list that there is no data

**Comment by phoenixbox** [comment]
@Shakarang you can find the conditions to make the empty view render [here](https://github.com/FaridSafi/react-native-gifted-listview/blob/9f6172d668a7e3c587c1c5d208a41b4a3c556dbe/GiftedListView.js#L283)
- An empty array passed to the _onFetch function of the GiftedListView will render its empty view.
- NOTE: you have to pass a function which returns a Component as the prop named `emptyView` to your GiftedListView

```
_onFetch(page = 1, listViewCallback, options) {
    let listItems = [];
    /**
     * implement your logic here to replace the listItems collection with your data
    */
    listViewCallback(listItems);
 }
_renderEmptyView(refreshCallback) {
    return (
      <View style={styles.defaultView}>
        <Text style={styles.defaultViewTitle}>Nothing here!</Text>
        <TouchableHighlight underlayColor='#c8c7cc'
          onPress={refreshCallback}>
          <Text>↻</Text>
        </TouchableHighlight>
      </View>
    );
 }
render() {
  return (
    <GiftedListView ref={(listView) => {this._listView = listView}}
    emptyView={this._renderEmptyView.bind(this)}/>
  )
}
```

**Comment by iamdurui** [comment]
@phoenixbox @FaridSafi When  the page don't  have any content, it is always flashing,thanks
code ：
 _onFetch(page=1 , callback, options) {
        console.log(this.state.noData);
            postLogin(Config.homeGetProjectListURL,authorizationData,this.initializeValue(page),(obj)=> {
                console.log(obj);
                console.log(page);
                if (obj.data.length===0){
                    callback(obj.data);
                }
                if (obj.data.length < 4 && obj.data.length>0) {
                    callback(obj.data, {
                        allLoaded: true, // the end of the list is reached
                    });
                } else {
                    callback(obj.data);
                }
            },(error)=> {
                console.log(error);
            });
    }
the rusult is refreshing the header,How to solve this problem
