### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ColinEberhardt** [FaridSafi/react-native-gifted-listview#62]
Great component! Your current release on npm is quite far behind. How about publishing a update?

**Comment by Andreyco** [comment]
Also, I'd like to ask, whether you plan to maintain this project? TY for response.

**Comment by FaridSafi** [comment]
Hello, I am working on a new set of components (including List, Forms, etc).
In the meantime, if someone wants to maintain this package please let me know

**Comment by ColinEberhardt** [comment]
OK - no worries. 

For your new components, I'd strongly recommend using semantic release:

https://github.com/semantic-release/semantic-release

Once configured (which is very easy via the CLI) all of your releases are fully automated. Any merge to 'master' will be released to npm with complete release notes. That way you'll never get people raising issues like this again!

**Comment by FaridSafi** [comment]
Thank you @ColinEberhardt semantic-release looks great
