### ISSUE TITLE
headerView / renderHeader not working

### ISSUE THREAD

**Issue by ghost** [FaridSafi/react-native-gifted-listview#7]
Hello,

I have a simple headerView I want to add to the top of the list (it's basically a featured post in a list of posts).

I'm adding the headerView, but it won't show for me:

My GiftedListView:

```
 <GiftedListView
      ref="PostView"
      initialListSize={20}
      onFetch={this.loadData}
      dataSource={this.state.postRows}
      onEndReachedThreshold={200}
      onEndReached={this.addMorePosts.bind(this)}
      rowView={this.renderPost.bind(this, this.props.navigator)}
      pagination
      withSections={false}
      refreshable={false}
      headerView={this.renderHeader}
    />
```

and my renderHeader, the console log message won't show either:

```
renderHeader() {
  console.log('does it render?');
  return (
    <View>
      <Text>Test</Text>
    </View>
  );
}
```

I tried looking at your code and saw on line 404:

```
 renderHeader={this.props.refreshable === true && Platform.OS !== 'android' ? this._renderRefreshView : this.headerView}
```

if I change this.headerView to this.props.headerView it works:

```
 renderHeader={this.props.refreshable === true && Platform.OS !== 'android' ? this._renderRefreshView : this.props.headerView}
```

I'm not sure if it will have any other consequences though, haven't looked trough the entire code and never made a PR before, although I can probably do it :).

EDIT:

I also see you're checking if the Platform is android or not. Is there any specific reason for that? I want to be able to show the renderHeader on both iOS and Android.

**Comment by FaridSafi** [comment]
Hello @txix, I noticed that you use the dataSource prop and I don't think it's supported.
The rows has to be updated by the component itself to update some internal states (I think the paginationStatus is not updated so the headerView is not displayed)

I think you already checked the examples
https://github.com/FaridSafi/react-native-gifted-listview/blob/master/GiftedListViewExample/example_simple.js
https://github.com/FaridSafi/react-native-gifted-listview/blob/master/GiftedListViewExample/example_advanced.js

Are you calling callback(rows) inside the onFetch method ?

Also I can't tell if the onEndReached prop is supported, the component already provides a built-in pagination system that you can use if you want

**Comment by ghost** [comment]
Hello! Thanks for your reply.

I was using a different ListView plugin first and tried to use the same logic (that's where the other properties are from). 

I thought those properties could have nothing to do with it, but if you say it's based on the paginationStatus, I have to implement it more properly I suppose! :)

I'll be looking at it today and will let you know if it's still an issue or not.

**Comment by FaridSafi** [comment]
Please re-open if you still have the issue
