### ISSUE TITLE
more active maintainer ?

### ISSUE THREAD

**Issue by halloulpsx** [FaridSafi/react-native-gifted-listview#73]
i think this repo need a more active maintainer

**Comment by sjafri5** [comment]
+1

**Comment by XHTeng** [comment]
+10086

**Comment by EQuimper** [comment]
+1

**Comment by scazzy** [comment]
I've been added as a maintainer of this repo at moment.
Will look into resolving most of the issues first, merge valid and helpful PRs, and also upgrading to ES6 syntax.
Feel free to add suggestions.

**Comment by scazzy** [comment]
Probably we'll need another maintainer. I can't fix much unless the npm registry isn't updated.
The lib is primarily used via npm which still remains outdated.
Open for thoughts
