### ISSUE TITLE
"ActivityIndicatorIOS is deprecated"

### ISSUE THREAD

**Issue by peacechen** [FaridSafi/react-native-gifted-listview#78]
React Native 0.34.1 spews a warning in the console:
**YellowBox.js:69 ActivityIndicatorIOS is deprecated. Use ActivityIndicator instead.**

This was noted in https://github.com/FaridSafi/react-native-gifted-spinner/issues/9 and the solution was to use ActivityIndicator instead.  However the version of _react-native-gifted-listview_ published to npm still depends on _react-native-gifted-spinner_.

**Comment by scazzy** [comment]
@peacechen this is fixed in 9b8d939e0feadd728e44fe865c36c524ff6a3a77. The new ActivityIndicator component removes dependency on GiftedSpinner

**Comment by peacechen** [comment]
Thanks @scazzy .   Would you mind publishing the updated version to npm?
