### ISSUE TITLE
in RN version 0.37  run example with error GiftedSpinner

### ISSUE THREAD

**Issue by testxin** [FaridSafi/react-native-gifted-listview#79]
to fixed  'react-native-gifted-spinner'  ActivityIndicatorIOS=> ActivityIndicator fixed problem

**Comment by lin493369** [comment]
Perfect solve my problem.Why it does't change in new upgrade.

**Comment by peacechen** [comment]
PR #74 is a couple months old and addresses this.  It removes GiftedSpinner entirely and uses the native ActivityIndicator.  There are 17 open PR's piled up!  The author FaridSafi should transfer this repo and the npm published package to someone who can maintain it.

**Comment by isxiaohu** [comment]
Seems you're trying to access 'ReactNative.createClass'.....'' of 'GiftedSpinner'     ----is this error?
