### ISSUE TITLE
Is there any possibility to upgrade to ES6?

### ISSUE THREAD

**Issue by liuxiaopai** [FaridSafi/react-native-gifted-listview#80]
Is there any possibility to upgrade to ES6? Thanks.

**Comment by scazzy** [comment]
@liuxiaopai working on this.

**Comment by scazzy** [comment]
@liuxiaopai 
Can you test the ES6 upgrade for this repo. If bugs, please raise. Once stable, can merge with the master repo.
https://github.com/scazzy/react-native-gifted-listview/blob/master/GiftedListView.js
