### ISSUE TITLE
Dependency error - GiftedSpinner

### ISSUE THREAD

**Issue by scazzy** [FaridSafi/react-native-gifted-listview#85]
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `GiftedSpinner`.

![image](https://cloud.githubusercontent.com/assets/1681586/21342228/e4b1ceee-c6b6-11e6-8c53-f0f5808a1734.png)

**Comment by sunkehappy** [comment]
I got the same error, is there something wrong?

**Comment by scazzy** [comment]
@sunkehappy This error is fixed in 9b8d939e0feadd728e44fe865c36c524ff6a3a77

**Comment by sunkehappy** [comment]
Is this released? How would I fix this on my local?

**Comment by scazzy** [comment]
@sunkehappy It's not yet published on the npm yet. We'll do so once upgraded in ES6 syntax.
Meanwhile, you can `npm uninstall` the existing repo, and instead install using
`npm install https://github.com/FaridSafi/react-native-gifted-listview.git`. Your code remains the same, just the repo source is changed.

You can also make manual change in node_modules as a temporary solution, but would not recommend that.
