### ISSUE TITLE
Add project managers 

### ISSUE THREAD

**Issue by scazzy** [FaridSafi/react-native-gifted-listview#86]
There are many pull requests pending. Would suggest you add more project managers to keep the repo updated or transfer the repository to an active contributor.
@FaridSafi

**Comment by FaridSafi** [comment]
Sorry I couldn't manage this repo recently. Is anyone interested in maintaining it?

**Comment by scazzy** [comment]
@FaridSafi I wouldn't mind. Also if you have seen anyone active on this repo until now.
