### ISSUE TITLE
GiftedSpinner Error

### ISSUE THREAD

**Issue by isxiaohu** [FaridSafi/react-native-gifted-listview#88]
Error message:Element type is invalid:expected a string....Check the render method of 'GiftedSpinner'. What should i do?

**Comment by hanlike** [comment]
+1

**Comment by scazzy** [comment]
@isxiaohu @thecorsair this is fixed in 9b8d939e0feadd728e44fe865c36c524ff6a3a77. You can npm install the module from git directly until it's published on npm

**Comment by aitchkhan** [comment]
@scazzy can we close this issue then?

**Comment by xwartz** [comment]
Why not published on npm?

**Comment by scazzy** [comment]
@xwartz the repo owner isn't responding to publish request.
